### ISSUE TITLE
No Audio

### ISSUE THREAD

**Issue by Volconon** [drauger-os-development/steam-login-session#2]
Don't know why this is happening, and I can't access terminal; but when I login there's a complete lack of audio, and no way to access bluetooth settings...

Any help?

**Comment by Batcastle** [comment]
Hi! Sorry it took so long to respond. Just now saw this. Do you have any way to try audio over AUX or HDMI/DisplayPort?

**Comment by Volconon** [comment]
I can get it to work if I set it to aux in my main sustem before rebooting into the steam session, but I have to reboot for that to work, I have an hdmi port, but no way to test it…😅

**Comment by Batcastle** [comment]
Alright. I'm seeing your issue and found a solution. I have a commit in the works to fix the issue. Won't be too long till an update is available.

**Comment by Batcastle** [comment]
Alright. So if you will check the message from the last commit, you will see that the fix to your issue actually creates other issues. I have created a configuration file where you can disable or enable that fix as desired, by simply setting the `steam_os_mode` field to `true` in `/etc/steam-login-session/settings.json`.

This way, the other issues created by the fix for your issue will not affect everyone, and you and others who experience this bug can simply make a quick edit to a file and potentially fix your audio issues.
